[project]
name = "observing-happiness"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "beautifulsoup4>=4.14.0",
    "fastapi>=0.114.2",
    "requests>=2.32.5",
    "uvicorn>=0.30.5",
]
